-- MySQL Script generated by MySQL Workbench
-- 01/22/15 15:36:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema book
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema book
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book` DEFAULT CHARACTER SET utf8;
USE `book` ;

-- -----------------------------------------------------
-- Table `book`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book`.`items` (
  `id` VARCHAR(20) NOT NULL,
  `title` VARCHAR(1024) NULL DEFAULT NULL,
  `creator` VARCHAR(1024) NULL DEFAULT NULL,
  `lang` VARCHAR(5) NULL DEFAULT NULL,
  `date_created` DATE NULL DEFAULT NULL,
  `subject` VARCHAR(1024) NULL DEFAULT NULL,
  `web_page` VARCHAR(1024) NULL DEFAULT NULL,
  `download_quantity` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `items_date_created_idx` (`date_created` ASC),
  INDEX `items_download_qty_idx` (`download_quantity` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `book`.`user_item_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book`.`user_item_ratings` (
  `user_id` DOUBLE NOT NULL,
  `item_id` VARCHAR(20) NOT NULL,
  `rating` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `item_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `book`.`user_item_recommendations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book`.`user_item_recommendations` (
  `user_id` DOUBLE NOT NULL,
  `item_id` VARCHAR(20) NOT NULL,
  `rating` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `item_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `book`.`user_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book`.`user_items` (
  `user_id` DOUBLE NOT NULL,
  `item_id` VARCHAR(20) NOT NULL,
  `rated_flag` CHAR(1) NOT NULL,
  PRIMARY KEY (`user_id`, `item_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `book`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book`.`users` (
  `user_id` DOUBLE NOT NULL AUTO_INCREMENT,
  `date_created` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;

CREATE VIEW `book`.`subjects_vw` as (
       SELECT distinct(substring_index(subject, '--',1)) as short_subject 
       FROM items 
);

CREATE VIEW `book`.`authors_vw` as (
       SELECT distinct(creator) as author
       FROM items 
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
