package com.impactsoftware.bookutilities;

import java.io.BufferedReader;
import java.io.FileReader;

import org.cloudi.API;

/**
 * ItemPrediction is responsible for loading item predictions generated by the
 * Recommendation engine into the database.
 *
 * @author Bruce Kissinger, 2012
 */
public class ItemPrediction {
    public ItemPrediction() {
        super();
    }

    public void load(String filename, API api) {        
        RecommendationData recommendationData = new RecommendationData();
        recommendationData.setCloudIAPI(api);

        recommendationData.clearUserItemRecommendations();

        try {
            BufferedReader reader =
                new BufferedReader(new FileReader(filename));

            String line = null;
            while ((line = reader.readLine()) != null) {
                //System.out.println("Read " + line);
                // Note: the format of the string is: user_id [item:rating,item:rating...]

                // first parse the user_id
                String[] results1 = line.split("\t");
                // todo: check size of results array

                String user_id = results1[0];
                //System.out.println("User ID: " + user_id);

                String temp = results1[1];
                String ratings = temp.substring(1, temp.length() - 1);
                //System.out.println("Temp: |" + ratings + "|");

                String[] results2 = ratings.split(",");
                for (int i = 0; i < results2.length; ++i) {
                    //System.out.println("Result " + i + "=" + results2[i]);
                    String[] results3 = results2[i].split(":");
                    
                    //System.out.println("Results3[0] " + results3[0]);
                    //System.out.println("Results3[1] " + results3[1]);
                   
		    if (results3.length >= 2) { 
                    	recommendationData.saveUserItemRecommendation(user_id, results3[0], results3[1]);
		    }
                }

            }
            reader.close();

        } catch (java.io.FileNotFoundException ex) {
            System.out.println("File not found " + filename);            
        } catch (java.io.IOException ex2) {
            System.out.println("Error reading " + filename);            
        }
        
    }


}
